### ISSUE TITLE
Data specs

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/AFQ-Browser#10]
@anotherjoshsmith Write a data spec for the .csv file with data

**Comment by arokem** [comment]
Tabular with columns: tract, subject, position, value

The last column can be for example, the FA.

**Comment by arokem** [comment]
The directory structure we are going for is: 

```
client/
  |- data/
     |- subjects.csv
     |- nodes.csv
     |- subj001/
        |- bundles.json
        |- surface.obj
     |- subj002/
        |- bundles.json
        |- surface.obj
     |- ...
```

**Comment by arokem** [comment]
See also #20, #21, #19
