### ISSUE TITLE
errer in installation

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/AFQ-Browser#101]
@arokem I get the following error when I clone the repo and run python setup.py install

error: can't copy 'afqbrowser/site/client': doesn't exist or not a regular file

**Comment by arokem** [comment]
Interesting.

What do you get when you type the following:

    python -c"import sys; print(sys.version); import setuptools;
print(setuptools.__version__)"

**Comment by jyeatman** [comment]
2.7.11 |Anaconda 2.5.0 (x86_64)| (default, Dec  6 2015, 18:57:58)

[GCC 4.2.1 (Apple Inc. build 5577)]

19.6.2

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://brainandeducation.com

**Comment by arokem** [comment]
Aha - that might be the issue - pretty old setuptools you have there.

Could you please run `pip install --upgrade setuptools` first and then
retry the installation?

**Comment by arokem** [comment]
@jyeatman : were you able to install following the README instructions, after upgrading setuptools, or is this still an issue?

**Comment by jyeatman** [comment]
install yes. But it crashes on startup

File "/Users/jyeatman/anaconda/bin/afqbrowser-run", line 4, in <module>

    __import__('pkg_resources').run_script('AFQ-Browser==0.1.dev0',
'afqbrowser-run')

  File
"/Users/jyeatman/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 738, in run_script

    self.require(requires)[0].run_script(script_name, ns)

  File
"/Users/jyeatman/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 1499, in run_script

    exec(code, namespace, namespace)

  File
"/Users/jyeatman/anaconda/lib/python2.7/site-packages/AFQ_Browser-0.1.dev0-py2.7.egg/EGG-INFO/scripts/afqbrowser-run",
line 17, in <module>

    afqb.run(args.target, args.port)

  File
"/Users/jyeatman/anaconda/lib/python2.7/site-packages/AFQ_Browser-0.1.dev0-py2.7.egg/afqbrowser/browser.py",
line 151, in run

    os.chdir(site_dir)

OSError: [Errno 2] No such file or directory: './AFQ-browser/client'

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://brainandeducation.com

**Comment by arokem** [comment]
Did you run afqbrowser-assemble first?

**Comment by jyeatman** [comment]
Oh instructions there are unclear. So data is included as a .mat file only
then? Readme should be updated to contain the path to that file otherwise
that command doesn't run. After running it I can launch afq browser. But I
can't run it a second time on a new dataset because it won't overwrite the
data

Traceback (most recent call last):
  File "/home/jyeatman/anaconda2/bin/afqbrowser-assemble", line 4, in
<module>
    __import__('pkg_resources').run_script('AFQ-Browser==0.1.dev0',
'afqbrowser-assemble')
  File
"/home/jyeatman/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File
"/home/jyeatman/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 1499, in run_script
    exec(code, namespace, namespace)
  File
"/home/jyeatman/anaconda2/lib/python2.7/site-packages/AFQ_Browser-0.1.dev0-py2.7.egg/EGG-INFO/scripts/afqbrowser-assemble",
line 19, in <module>
    afqb.assemble(args.source, args.target)
  File
"/home/jyeatman/anaconda2/lib/python2.7/site-packages/AFQ_Browser-0.1.dev0-py2.7.egg/afqbrowser/browser.py",
line 140, in assemble
    shutil.copytree(data_path, site_dir)
  File "/home/jyeatman/anaconda2/lib/python2.7/shutil.py", line 177, in
copytree
    os.makedirs(dst)
  File "/home/jyeatman/anaconda2/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: './AFQ-browser'



Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://brainandeducation.com

**Comment by arokem** [comment]
Link to the data is in #102. 

The command line interface allows you to set the file-system location to write to and read from, so you can run this several times. But I agree that it should be crystal clear in the documentation. I am currently making another PR for more detailed documentation.

**Comment by jyeatman** [comment]
We should also allow for overwriting the data. I would have the default be
to overwrite rather than crash

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://brainandeducation.com

**Comment by arokem** [comment]
OK - that's implemented in #104
