### ISSUE TITLE
losing last column of nodes table

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/AFQ-Browser#119]
@anotherjoshsmith @richford Whatever is the final column in the nodes.csv table is not showing up in the "Plot Type" drop down menu. In other words, we are somehow losing one of the values (in the case of my current data it is md, but it seems to be whatever is the last column in nodes.csv)

**Comment by anotherjoshsmith** [comment]
Oops, falling back on my python instincts for slicing! In javascript array.slice(3,-1) slices to the second to last element whereas array.slice(3) slices through the end. I'll fix it now!

**Comment by jyeatman** [comment]
I'll take a look at the PR once you submit it

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://brainandeducation.com

**Comment by arokem** [comment]
Closed through #121
