### ISSUE TITLE
"About the data" box

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/AFQ-Browser#122]
We need some place to provide information about the study that is being described by an AFQ-Browser instance. For example, for the demo we currently have, we might want to point to the Weston Havens data, and related publications.

**Comment by jyeatman** [comment]
Can this added to the title bar with a prominent citation and link to a published manuscript?

**Comment by jyeatman** [comment]
@anotherjoshsmith @arokem Can we have the text in the title bar be read in from a .txt or .json file? That way when we create a new AFQ-Browser instance for published work we could include the title, authors and journal of the publication

**Comment by arokem** [comment]
Potentially use something like [jinja](http://jinja.pocoo.org/) to template this? That is, ask users a couple of questions as they run the "assemble" part, and then inject that into the html that gets generated? Otherwise, creating a side-car file that contains this metadata file also works.

**Comment by richford** [comment]
The `afqbrowser-assemble` command should edit the settings.json file to change the title, title hyperlink, subtitle, and subtitle hyperlink (if applicable). The appropriate properties to change in settings.json are:

`global.html.title`
`global.html.link`
`global.html.subtitle`
`global.html.sublink`

**Comment by arokem** [comment]
The Python CLI should read in the default settings file, edit these based on input on the command line, and overwrite the `settings.json` file, before assembling the whole thing.

**Comment by jyeatman** [comment]
This issue was only partially taken care of. In line with comments from Reviewer #3 we should implement and "about the data box" and store acquisition parameters associated with the data

**Comment by richford** [comment]
Redundant issue. See #170.
