### ISSUE TITLE
Mouse hoverover for zoom

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/AFQ-Browser#138]
@anotherjoshsmith Zoom is looking good. One final issue we had discussed was changing the mouse hoverover when it is over the axis so that users know they can zoom. @arokem suggested a certain mouse icon

**Comment by arokem** [comment]
How about "row-resize"?

See:
https://www.w3schools.com/cssref/playit.asp?filename=playcss_cursor&preval=initial

**Comment by jyeatman** [comment]
That makes sense

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://brainandeducation.com

**Comment by anotherjoshsmith** [comment]
@jyeatman Thanks, forgot that part again! I'll create a plotFormat branch to solve this along with the labeling issues in #126

**Comment by anotherjoshsmith** [comment]
Addressed in #145.
