### ISSUE TITLE
Git housekeeping

### ISSUE THREAD

**Issue by richford** [yeatmanlab/AFQ-Browser#15]
We have a couple development branches left over from previous merges and pull requests. Do we still need the [original viz](https://github.com/yeatmanlab/AFQ-viz/tree/original-viz) or [tracklist](https://github.com/yeatmanlab/AFQ-viz/tree/tracklist) branches? I recommend we follow the guidelines in [this tutorial](http://railsware.com/blog/2014/08/11/git-housekeeping-tutorial-clean-up-outdated-branches-in-local-and-remote-repositories/) to clean up the unused branches. @anotherjoshsmith you have the latest commits on both of these branches. [original viz](https://github.com/yeatmanlab/AFQ-viz/tree/original-viz) has been merged and its last commit was 7 weeks ago. [tracklist](https://github.com/yeatmanlab/AFQ-viz/tree/tracklist) hasn't been merged into master and its last commit was 8 weeks ago. Is it okay to delete these?

**Comment by richford** [comment]
@anotherjoshsmith I assigned this to you since you have the last commits and I want to make sure we're not losing anything that you committed but that hasn't yet been merged.

**Comment by anotherjoshsmith** [comment]
@richford Great! There's nothing we need in those two branches, I'll take care of them.
