### ISSUE TITLE
Allow user to select from a drop down menu of pre-filled settings

### ISSUE THREAD

**Issue by richford** [yeatmanlab/AFQ-Browser#155]
Create a settings directory
Use drop down menu to call `afqb.global.readsettings()` function.

**Comment by jyeatman** [comment]
@richford I think the default behavior should be to load the settings file in the directory. I noticed that when I save the settings.json file (or replace lines in the file) that these changes aren't reflected until I click the "load settings" button. For example, if the "title" attribute is edited in the settings, we want that to show up as the default for the afq-browser instance

**Comment by richford** [comment]
Yeah, if you have the browser open and are editing the settings.json file at the same time, you'll have to use the "load settings" button for those changes to be reflected in the browser. Alternatively, if you refresh the browser, it should see the changes that you made.

I don't know of a way to make the browser continuously observe the settings.json file for changes.

**Comment by jyeatman** [comment]
My issue was that when I refresh the browser it doesn't load the settings (such as the title) unless I click load settings

**Comment by richford** [comment]
Thanks for pointing that out. I'll submit a PR that fixes this (and the same issue with mouseover highlight).

**Comment by richford** [comment]
PR submitted. We should keep this issue open even after accepting PR #157 since it doesn't add the dropdown menu. Thanks for pointing out that issue @jyeatman.

**Comment by richford** [comment]
This is not for the neuroimaging paper milestone, correct? We may very well fix it before the paper is accepted, but is it important to fix this before the paper is initially submitted?

**Comment by jyeatman** [comment]
I dont' think so

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://brainandeducation.com

**Comment by richford** [comment]
After further conversation, wait until the resolution of #167.

**Comment by richford** [comment]
Obviated by #185.
