### ISSUE TITLE
Add support for FSL/TRACULA

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/AFQ-Browser#163]
TRACULA (Yendik, et al., 2011) is an automated pipeline to conduct a tract-based analysis of diffusion properties using FSL's diffusion tools and Freesurfer's anatomical pipeline. To make AFQ-Browser compatible with TRACULA's output we need:

- [ ] Python code to read TRACULA stats table and write out in tidy data format for AFQ-Browser. See TRACULA example data available here:
 ftp://surfer.nmr.mgh.harvard.edu/pub/data/diffusion_tutorial.tar.gz

- [ ] 3d anatomy view of TRACULA ROIs. This could be done  average MNI locations that are saved in the TRACULA stats folder. See here for example of rendering of [TRACULA nodes](https://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/TraculaStatistics). dat GUI to select fibers or ultratube and AFQ or TRACULA render in 3js window

- [ ] afqbrowser-assemble will write out fibers and ultrafiber from inputs. If left blank, we will use the hardcoded data

- [ ] add a default afq ultratube

- [ ] can keys be written as strings and that is used to populate other fields? This will handle the difference in number of fiber groups between afq and tracula. And it will be forward looking for new fiber groups

**Comment by richford** [comment]
For the 3D Panel, I'm thinking that we'll have a "Fiber Representation" selector in the 3D gui control panel. When "all fibers" is selected, the behavior is as usual and "Fiber Opacity" controls the opacity of the individual streamlines. The core tubes are invisible. When "core fiber" is selected, the streamlines are invisible and "Fiber Opacity" controls that opacity of the core fibers.

<img width="668" alt="3d_panel_with_ultratube" src="https://user-images.githubusercontent.com/7978135/33056607-631d7fbc-ce3b-11e7-85a9-646e641aca3e.png">

I think this is the simplest interface. One disadvantage is that the user won't be able to show core fibers and streamlines at the same time. But after playing around a bit with the core fibers, I think that would be of limited utility anyway.

@arokem, @jyeatman, @anotherjoshsmith, @akeshavan: Your thoughts?

**Comment by jyeatman** [comment]
Would the alternative be to have two independent sliders for controlling
core fiber opacity and all fiber opacity? It might be nice to be able to
see where the core fiber representation is relative to the whole fiber
group. For example if we were to examine different ways to compute the core
fiber. But I think either works fine
-- 
Sent from a mobile device. Please excuse typos

**Comment by richford** [comment]
Resolved by #181
