### ISSUE TITLE
Improve documentation for users and developers

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/AFQ-Browser#164]
[AFQ-Browser documentation](https://yeatmanlab.github.io/AFQ-Browser/) should be improved to include more information to support other developers in incorporating AFQ-Browser into their software projects.

**Comment by arokem** [comment]
Use [doctr](https://drdoctr.github.io/doctr/) to automate documentation build

We do also need to add content: 

- [x] Data specification. 
- [x] How would I use this with data from another software (not AFQ)?
- [x] How would you contribute to this project? 
- [x] Python API
- [x] What are things that you can switch out, if you want to?
- [x] Link to the preprint (and eventually to paper)
- [x] What are the moving pieces in the Javascript part ( @richford )? 
- [x] I want to add an AFQ-browser into my lab website. How do I do that?
- [x] How do I cite the AFQ-browser project

**Comment by richford** [comment]
@anotherjoshsmith and I should write documentation for each `js` file.

**Comment by richford** [comment]
javascript documentation added in #226 and #228.

**Comment by arokem** [comment]
People shouldn't put these on their lab website, because it would break afqvault and binder.

**Comment by arokem** [comment]
OK - all of these are handled in #234, which I believe is now ready to go!

**Comment by richford** [comment]
Resolved by #252.
