### ISSUE TITLE
Centralized AFQ-Browser data repository

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/AFQ-Browser#166]
In line with neurovault, we need to develop a centralized repository that agregates data from published instances of AFQ-Browser. This should be done automatically (with user approval) in the afqbrowser-publish function. @akeshavan had ideas for a simple database system. This database should also include fields for imaging parameters that are stored alongside the data. We can use a similar form as neurovalut but with specific fields for diffusion MRI sequences (e.g., storing b-vecs table). Ideally, there would be an option to populate these fields by parsing a DICOM file.

**Comment by richford** [comment]
Resolved at [github.com/afqvault/afqvault](github.com/afqvault/afqvault)

Remaining work captured in #170.
