### ISSUE TITLE
URL query string

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/AFQ-Browser#167]
Rather than settings file, save into URL query string

**Comment by jyeatman** [comment]
Somehow handle prioritizing query string versus settings file. One thing to note is that we need to keep a way to edit the title of the page to have the citation and link in it. Piggy back editing the title on the dat GUI

**Comment by akeshavan** [comment]
https://github.com/ljharb/qs

**Comment by jyeatman** [comment]
query string gets populated based on settings in settings.json file

**Comment by richford** [comment]
@akeshavan I think that the qs.min.js file you committed is from https://github.com/nire0510/qs, which explains the API differences we were seeing yesterday. The one you referenced above (https://github.com/ljharb/qs) has a nice stringify method that makes readable strings when you use the `{encode: false}` option. We might wind up using both. We can talk more about it at our meeting today.
