### ISSUE TITLE
What happens if there's no query string

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/AFQ-Browser#198]
Trying to visit the Sarica 2017 without a query string: 

https://yeatmanlab.github.io/Sarica_2017/

and I get the spinning wheel go on for ever. 

No problem when visiting with the query string: https://yeatmanlab.github.io/Sarica_2017/?table[prevSort][key]=&table[prevSort][order]=ascending&table[prevSort][count]=2&table[sort][key]=&table[sort][order]=descending&table[sort][count]=2&plots[zoom][rd][scale]=1&plots[zoom][rd][translate][0]=0&plots[zoom][rd][translate][1]=0

Where does that get populated from? The merge of new stuff from upstream was kind of messy (see history here: https://github.com/yeatmanlab/Sarica_2017/network). Did I drop something crucial along the way?

**Comment by richford** [comment]
When there is no querystring, settings get populated from `settings.json`. Oddly enough, I don't get the same error when I go to https://yeatmanlab.github.io/Sarica_2017/

**Comment by arokem** [comment]
Must be my $@!# cache.
