### ISSUE TITLE
Z-scores

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/AFQ-Browser#204]
Reviewer point below. I've been thinking about how to implement z-scores without it being unwieldy and haven't come to a good solution. One idea would be to have this in the mouse hover-over for the individual tract details. Right now when the mouse hovers over an individual's plot it gets highlighted. We could also display the subject's z-score relative to each of the group means and standard deviations. @arokem @akeshavan @richford @anotherjoshsmith what do you think? Is there an elegant way to add this feature, or is it too much for the current release?

Authors emphasized that one advantage of AFQ browser is that it allows individual subject data to be visualized, and that this may be particularly important for surgery, example. While it is true that individual subject tract and metadata can be selected and examined, in order to provide validity that an individual subject is different from group mean, some statistics such as tract, brushing or node-level z-score should accompany each selected subject. It is not clear how the z-scores that authors quoted (e.g., text for Figure 4) were obtained or ascertained on AFQ browser.

**Comment by richford** [comment]
See [here](http://bl.ocks.org/bobmonteverde/2070123) and [here](http://www.d3noob.org/2014/07/my-favourite-tooltip-method-for-line.html) for examples. We could do this for z-scores at each node for each subject.

But I am concerned that adding this feature would make the 2D plots too busy. It's a tough call. Where should we draw that line between AFQ-Browser as an EDA/data sharing tool and AFQ-Browser as a more full-featured analysis tool? @jyeatman, you discussed this in your response to reviewer `#3` about side-by-side analysis using jupyter notebooks. What does everyone think, is this the sort of thing that should be implemented in AFQ-Browser, or should it be done elsewhere?

**Comment by jyeatman** [comment]
I think the "A Simple D3 Line chart with Legend and Tooltips" is awesome. If it could be a checkbox like Brushable Tracts, then I think it would be useful without adding too much clutter. But it does also go beyond the scope of the work. But, in this case, it might also be difficult to avoid this suggestion

**Comment by akeshavan** [comment]
@richford @anotherjoshsmith : for some reason I can't remember how to access the bins of the quantiles from groupScale! I know I had it earlier today, but I didn't write it down correctly or something. Here is the progress so far: https://github.com/yeatmanlab/AFQ-Browser/pull/216

**Comment by richford** [comment]
@akeshavan Responded inline on PR #216

**Comment by richford** [comment]
Resolved with #216
