### ISSUE TITLE
Format tooltip z-score

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/AFQ-Browser#246]
@akeshavan It looks like more spacing than intended in between the subject and z-score

![image](https://user-images.githubusercontent.com/1775818/34185723-dfe6986a-e4db-11e7-9550-154ece539c4a.png)

**Comment by akeshavan** [comment]
Time to buy a new computer, your resolution isn't good! JK, converted units, try this one: https://github.com/yeatmanlab/AFQ-Browser/pull/251
