### ISSUE TITLE
Decimal places

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/AFQ-Browser#247]
@arokem @richford @anotherjoshsmith The metadata table now shows 6 decimal places. Before we were doing something different because age just showed up as an integer (eg, 7 rather than 7.000000). Is there a good way to determine how to format the table? I can understand why we might want better precision. But in most instances it will just look weird to have that many zeros

**Comment by richford** [comment]
This is a result of the formatting decisions made in #187. It's a one liner to change the number of decimal places. Just let me know what precision is best. Also, if you want, I can check if the whole column is full of integers and take away the decimal places in that case. That's more than a one-liner but should be fairly straight-forward.

**Comment by jyeatman** [comment]
Can we show as many decimal places as are defIndeed in the data? Otherwise
I would probably display  2 decimal places or an integer
-- 
Sent from a mobile device. Please excuse typos
