### ISSUE TITLE
z-score bug

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/AFQ-Browser#254]
@akeshavan Looks like an issue with z-score calculations. In the first screenshot, the subject that is at least 4 standard deviations below the mean is showing up as a z-score of 0.82. In the second screenshot the subject that is at the mean is showing up as a very large z-score. [See this AFQ-Browser instance](https://yeatmanlab.github.io/AFQBrowser-demo/?table[prevSort][count]=2&table[prevSort][order]=ascending&table[prevSort][key]=&table[sort][count]=2&table[sort][order]=ascending&table[sort][key]=Age&table[selectedRows][subject_040]=true&table[selectedRows][subject_029]=true&table[selectedRows][subject_036]=true&plots[checkboxes][left-corticospinal]=true&plots[checkboxes][left-cingulum-cingulate]=true&plots[checkboxes][left-ifof]=true&plots[checkboxes][left-uncinate]=true&plots[zoom][rd][scale]=1&plots[zoom][rd][translate][0]=0&plots[zoom][rd][translate][1]=0&plots[zoom][fa][scale]=1&plots[zoom][fa][translate][0]=0&plots[zoom][fa][translate][1]=0&plots[plotKey]=fa&plots[lineOpacity]=0.15&three[cameraPosition][x]=-9.313489721456122&three[cameraPosition][y]=0.1858948616761763&three[cameraPosition][z]=0.13682361007740584)

![image](https://user-images.githubusercontent.com/1775818/34500673-9f87c5ec-efc0-11e7-868a-1a0dd31873bd.png)
![image](https://user-images.githubusercontent.com/1775818/34500689-a99bc0e2-efc0-11e7-9b5f-8da3130e3f42.png)

**Comment by jyeatman** [comment]
@richford @anotherjoshsmith Do either of you have an idea for this bug? My guess is an indexing issue. check out node 37 in the highlighted subject. Once we fix this I will resubmit the manuscript

https://yeatmanlab.github.io/AFQBrowser-demo/?table[prevSort][count]=2&table[prevSort][order]=ascending&table[prevSort][key]=&table[sort][count]=2&table[sort][order]=ascending&table[sort][key]=Age&table[selectedRows][subject_040]=true&plots[checkboxes][left-cingulum-cingulate]=true&plots[plotKey]=fa&plots[zoom][fa][scale]=1&plots[zoom][fa][translate][0]=0&plots[zoom][fa][translate][1]=0

**Comment by richford** [comment]
Resolved in #257 (I hope).
