### ISSUE TITLE
Control height of dat.GUI control panel

### ISSUE THREAD

**Issue by richford** [yeatmanlab/AFQ-Browser#26]
On @arokem's browser, the expanded control panel is not big enough to fit all of the controls and one has to scroll to reach them.

**Comment by richford** [comment]
I suspect that the control panel height is being adjusted as the window is being resized. @arokem, can you verify this on your end? Does the height of the control box grow if you make the browser window taller?

**Comment by arokem** [comment]
It seems to be a bit more complicated than that. Resizing the window does
affect this, but it doesn't seem to be linear, and clicking in the window
also sometimes has an effect.

**Comment by arokem** [comment]
I should say: sometimes making the browser window smaller resolves this (so
non-linear :-D).

**Comment by arokem** [comment]
Closed through #29
