### ISSUE TITLE
Failing to build the docs

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/AFQ-Browser#269]
When running a `make html`, I currently get the following exception: 

```
Exception occurred:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'jsdoc': 'jsdoc'
```

This is after installing `numpydoc` and `sphinx_js` (following the error described in #268)

**Comment by richford** [comment]
Resolved in [403d51a](https://github.com/yeatmanlab/AFQ-Browser/pull/268/commits/403d51a6ea837da3eb814f77268ec1cb949c6f5e) of #268.
