### ISSUE TITLE
Some errors in using AFQ-Browser under Windows 10 system

### ISSUE THREAD

**Issue by ping-doctor** [yeatmanlab/AFQ-Browser#277]
AFQ-Browser is successfully installed under windows10 system with "pip install AFQ-Browser".  And ”afq.mat“ was downloaded from "https://yeatmanlab.github.io/AFQ-Browser/usage_guide.html" and was save to "F:\StudyData\AFQ_data".
Then when I run : ”afqbrowser-assemble  /F:\StudyData\AFQ_data/afq.mat“ in ”windows10 cmd“, some errors appear. How to use correctly under windows system?

**Comment by arokem** [comment]
What are the errors that you see? Could you please copy them here?

**Comment by ping-doctor** [comment]
First I run ”pip list“ to determine that AFQ-Browser was installed. 
C:\Users\Lenovo>pip list
Package         Version
--------------- --------
AFQ-Browser     0.2.4
certifi         2019.3.9
chardet         3.0.4
Deprecated      1.2.5
gitdb2          2.0.5
GitPython       2.1.11
idna            2.8
numpy           1.16.3
pandas          0.24.2
pip             19.1
PyGithub        1.43.7
PyJWT           1.7.1
python-dateutil 2.8.0
pytz            2019.1
requests        2.21.0
scipy           1.2.1
setuptools      40.8.0
six             1.12.0
smmap2          2.0.5
urllib3         1.24.2
wrapt           1.11.1
Then when I run : ”afqbrowser-assemble /F:\StudyData\AFQ_data/afq.mat“ in ”windows10 cmd“.  As follows：
C:\Users\Lenovo>afqbrowser-assemble /F:\StudyData\AFQ_data/afq.mat
'afqbrowser-assemble' is not an internal or external command, nor a runnable program or batch file.
So I tried to add the path of "afqbrowser-assemble" （”E:\Python_software\Python37\Scripts“）in the global environment variable and this error still occurs multiple times.

**Comment by ping-doctor** [comment]
I also tried to run "afqbrowser-assemble" with PyCharm, as follows：
E:\Python_software\Anaconda\python.exe E:/Python_software/Anaconda/Scripts/afqbrowser-assemble
Traceback (most recent call last):
  File "E:\Python_software\Anaconda\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could not be found。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/Python_software/Anaconda/Scripts/afqbrowser-assemble", line 4, in <module>
    import afqbrowser as afqb
  File "E:\Python_software\Anaconda\lib\site-packages\afqbrowser\__init__.py", line 1, in <module>
    from .browser import *  # noqa
  File "E:\Python_software\Anaconda\lib\site-packages\afqbrowser\browser.py", line 12, in <module>
    import scipy.io as sio
  File "E:\Python_software\Anaconda\lib\site-packages\scipy\__init__.py", line 62, in <module>
    from numpy import show_config as show_numpy_config
  File "E:\Python_software\Anaconda\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "E:\Python_software\Anaconda\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "E:\Python_software\Anaconda\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "E:\Python_software\Anaconda\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "E:\Python_software\Anaconda\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified module could not be found。

**Comment by ping-doctor** [comment]
I have solved it.

**Comment by arokem** [comment]
How did you solve this? Thanks!

**Comment by ping-doctor** [comment]
I didn't install GIT before; first I successfully installed GIT.
Then then started python in ”windows10 cmd“，imported afqbrowser module,run run afqbrowser.assemble and afqbrowser.run. As follows：

C:\Users\Lenovo>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import afqbrowser
>>> afqbrowser.assemble(r"F:\StudyData\AFQ_data\afq.mat",target=r"F:\StudyData\AFQ_data")
Page title [AFQ Browser]:
Page subtitle [None]:
Title hyperlink (including http(s)://) [None]:
Subtitle hyperlink (including http(s)://) [None]:
>>> afqbrowser.run(target=r"F:\StudyData\AFQ_data",port=8080)

**Comment by arokem** [comment]
Great. Thank you!
