### ISSUE TITLE
Add method to save state of the browser

### ISSUE THREAD

**Issue by richford** [yeatmanlab/AFQ-Browser#47]
Save:
- orientation of 3D brain
- selected tracts
- brushing
- subject selection
- sorting

**Comment by arokem** [comment]
This seems like a good start: http://stackoverflow.com/questions/33645587/capturing-saving-the-current-state-of-d3-js-visualization

**Comment by richford** [comment]
Change afqb object heirarchy to:
- afqb
  - settings
    - table
    - plots
    - three
  - data
    - table
    - plots
    - three
  - methods
    - table
    - plots
    - three
  - constants
    - table
    - plots
    - three

Then use dat.gui presets to save and change `afqb.settings`. Add button to download/upload a settings file and then regenerate the data by calling the methods in `afqb.methods`.

**Comment by richford** [comment]
Use YAML

**Comment by richford** [comment]
Resolved with #147
