### ISSUE TITLE
scrolling in meta data table

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/AFQ-Browser#93]
@richford @anotherjoshsmith Just noticed a bug in scrolling. For large tables, the arrow sliders only work when you are at the end of a table. For example if you try to scroll through the table width, it won't work until you have already scrolled down to the bottom of the table

**Comment by richford** [comment]
@jyeatman I don't see arrows on my scrollbar so I'm unable to reproduce this. I think it should be a quick fix but I can't make much progress because I don't know what to fix. Maybe this issue is only showing up on some browsers. Could you take a screenshot of this issue and post it here?

**Comment by jyeatman** [comment]
Sorry, no arrows, but the issue is with the whole scroll bar. Try using the
right hand scroll bar when you have a dataset that has more than 6 columns
loaded in.

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://brainandeducation.com

**Comment by jyeatman** [comment]
@richford @arokem I'm closing this issue because I can't reproduce it on other computers. I'm guessing this is a chrome-ubuntu issue so not worth spending our time tracking it down
