### ISSUE TITLE
Set y-axis range

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/AFQ-Browser#94]
I have started testing AFQ-Browser with various datasets which has helped me notice minor issues. Currently we set the axis scaling based on the range of the data for all subjects and all tracts. However, in many datasets, there is at least one outlier subject with crazy values on one tract. I think we should keep the initial axis scaling. But we also need a way to allow the user to define the range for the y-axis. @richford @anotherjoshsmith at one point we had an initial implementation of this feature but then we decided to deprecate it. And I  remember that we discussed whether this should be done dynamically or by defining numbers in the control bar that set the axis for all tracts. Do you remember what our thoughts were at the time?

**Comment by arokem** [comment]
Maybe use zooming instead (a la TensorBoard)?

**Comment by arokem** [comment]
Or Google-maps style zooming: 

http://bl.ocks.org/jgbos/9752277

Maybe simultaneous to brushing

**Comment by anotherjoshsmith** [comment]
Closed with #131
