### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/AFQ-Browser#96]
@arokem can you add install instructions to the readme so that someone could clone the repo, install the dependencies and launch the example data on localhost?

**Comment by arokem** [comment]
Once #95 is settled, we can set up sphinx documentation, which will include this. 

For the time being, I will also put this in the README on #95

**Comment by arokem** [comment]
For now: https://github.com/yeatmanlab/AFQ-Browser/pull/95/commits/3528cfdecc34b584bef789e9828bdc9a2b739121

**Comment by arokem** [comment]
This is resolved in the sphinx documentation, see #141
