### ISSUE TITLE
Option parsing error in afqbrowser-assemble

### ISSUE THREAD

**Issue by richford** [yeatmanlab/AFQ-Browser#99]
I think `opts.source` should be `args[0]` in this line of `afqbrowser-assemble`:

https://github.com/yeatmanlab/AFQ-Browser/blob/master/bin/afqbrowser-assemble#L15

I'll submit a pull request to fix this and will switch from optparse to argparse while I'm at it.

**Comment by arokem** [comment]
This was closed through #100
